services:
  frontend:
    build:
      context: ./src/app-frontend
    ports:
      - "5000:80"
    networks:
      - default-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    build:
      context: .
      dockerfile: src/app-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - frontend
    networks:
      - default-network
    extra_hosts:
      - "host.docker.internal:host-gateway"


networks:
  default-network:
    driver: bridge
