services:
  frontend:
    build:
      context: ./src/app-frontend
    ports:
      - "5000:5000"

  backend:
    build:
      context: .
      dockerfile: src/app-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - frontend
